app/flaskblog/users/routes.py
from flask import render_template, redirect, url_for, flash, request, Blueprint
from flaskblog import db, bcrypt
from flaskblog.users.forms import (RegisterForm, LoginForm, UpdateAccountForm, 
                            RequestToken, ResetPasswordForm)
from flaskblog.models import User
from flask_login import login_user, current_user, logout_user, login_required
from flaskblog.users.utils import save_image, send_mail

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegisterForm()
    if form.validate_on_submit():
        user1 = User.query.filter_by(username=form.username.data).first()
        user2 = User.query.filter_by(email=form.email.data).first()
        if user1 is not None:
            flash(f'This username is taken, Please choose another', 'danger')
        elif user2 is not None:
            flash(f'This mail id is taken, Please choose another', 'danger')
        else:
            hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user = User(username=form.username.data, email=form.email.data, password = hashed_password)
            db.session.add(user)
            db.session.commit()
            flash(f'Account created successfully', 'success')
            return redirect(url_for('users.login'))
    return render_template('register.html', form=form)

@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash(f'Login successfully', 'success')
            return redirect(url_for('main.home'))
        else:
            flash(f'Invalid Credintials!', 'danger')
    return render_template('login.html', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.login'))

@users.route('/about', methods=['GET', 'POST'])
@login_required
def about():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            file_name = save_image(form.picture.data, form.username.data)
            current_user.image_file = file_name
        user1 = User.query.filter_by(username=form.username.data).first()
        user2 = User.query.filter_by(email=form.email.data).first()
        if user1 and form.username.data != current_user.username:
            flash(f'This username is taken, Please choose another', 'danger')
        elif user2 and form.email.data != current_user.email:
            flash(f'This email id is taken, Please choose another', 'danger')
        else:
            current_user.username = form.username.data
            current_user.email = form.email.data
            db.session.commit()
            flash(f'Account details updated', 'success')
            return redirect(url_for('users.about'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pic/' + current_user.image_file)
    return render_template('about.html', image_file=image_file, form = form)

@users.route('/reset-password', methods=['GET', 'POST'])
def request_reset():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestToken()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is None:
            flash('This email id is not yet registered, sign-up required.', 'warning')
        else:
            send_mail(user)
            flash('A varification mail is send to your mail, reset password through the link in mail.', 'info')
            return redirect(url_for('users.login'))
    return render_template('request_token.html', form=form)

@users.route('/reset-password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = ResetPasswordForm()
    user = User.varify_token(token)
    if user is None:
        flash('your link is incorrect, or token expired, resend varification mail', 'warning')
        return redirect(url_for('users.request_reset'))
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', form=form)

app/flaskblog/templates/about.html
{% extends 'base.html' %}
{% block content %}
<h1>About Page</h1>
<div class="content-section">
    <div class="media">
        <img src="{{ image_file }}" alt="" class="rounded-circle account-img">
        <div class="media-body">
            <h2 class="account-heading"> {{ current_user.username }} </h2>
            <p class="text-secondary"> {{ current_user.email }} </p>
        </div>
    </div>
    <form action="" method="POST" enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.username.label(class='form-control-label') }}
            {%  if form.username.errors %}
                {{ form.username(class='form-control form-control-lg is-invalid') }}
                {% for error in form.username.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.username(class='form-control form-control-lg') }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.email.label(class='form-control-label') }}
            {%  if form.email.errors %}
                {{ form.email(class='form-control form-control-lg is-invalid') }}
                {% for error in form.email.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.email(class='form-control form-control-lg') }}
            {% endif %}
        </div><br>
        <div class="form-group">
            {{ form.picture.label() }}
            {{ form.picture(class="form-control-file") }}
            {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                    <span style="color: red;">{{ error }}</span><br>
                {% endfor %}
            {% endif %} <br>
        </div>
        <div class="form-group">
            {{ form.submit(class='btn btn-outline-info') }}
        </div>
    </form>
</div>

{% endblock content %}

app/flaskblog/templates/add_post.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section" style="width: 400px;">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.title.label(class='form-control-label') }}
            {%  if form.title.errors %}
                {{ form.title(class='form-control form-control-lg is-invalid') }}
                {% for error in form.title.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.title(class='form-control form-control-lg') }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.content.label(class='form-control-label') }}
            {%  if form.content.errors %}
                {{ form.content(class='form-control form-control-lg is-invalid') }}
                {% for error in form.content.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.content(class='form-control form-control-lg') }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class='btn btn-outline-info') }}
        </div>
    </form>
</div>
{% endblock %}

app/flaskblog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Flask blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
          
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                {% if current_user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item"><a class="nav-link" href="/about">profile</a></li>
                    <li class="nav-item"><a class="nav-link" href="/add-post">Add New Post</a></li>
                    <li class="nav-item"><a class="nav-link" href="/logout">Log out</a></li>                
                {% endif %}
            </div>
          </nav>
    </header>
    <div class="container">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        {% endwith %}

        {% block content %}{% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>

</body>
</html>

app/flaskblog/templates/home.html
{% extends 'base.html' %}
{% block content %}
<h1>Home Page</h1>

{% for post in posts %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <h2> {{ post.author.username }} </h2>
                {% if post.author == current_user %}
                    <a href="/update-post/{{post.id}}" style="text-decoration: none;"><button class="btn-info" >Update</button></a>
                    <a href="/delete-post/{{post.id}}" style="text-decoration: none;"><button class="btn-danger">Delete</button></a>
                    <br>
                {% endif %}
                <small class="text-muted"> {{ post.date_posted.strftime('%d-%m-%y') }} </small>
            </div>
            <h3> {{ post.title }}</h3>
            <p class="article-content"> {{ post.content }} </p>
        </div>
    </article>
    <br>
{% endfor %}

{% endblock content %}

app/flaskblog/templates/login.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section" style="width: 400px;">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.email.label(class='form-control-label') }}
            {%  if form.email.errors %}
                {{ form.email(class='form-control form-control-lg is-invalid') }}
                {% for error in form.email.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.email(class='form-control form-control-lg') }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password.label(class='form-control-label') }}
            {%  if form.password.errors %}
                {{ form.password(class='form-control form-control-lg is-invalid') }}
                {% for error in form.password.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.password(class='form-control form-control-lg') }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.remember.label(class='form-control-label') }}
            {{ form.remember(class='form-check-input') }}
        </div>
        <div class="form-group">
            {{ form.login(class='btn btn-outline-info') }}
            <a href="{{ url_for('users.request_reset') }}">forgot password</a>
        </div>
    </form>
    <div class="border-top">
        <small>
            New Here? <a href="{{ url_for('users.register') }}">Sign up</a>
        </small>
    </div>
</div>
{% endblock %}

app/flaskblog/templates/register.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section" style="width: 400px;">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.username.label(class='form-control-label') }}
            {%  if form.username.errors %}
                {{ form.username(class='form-control form-control-lg is-invalid') }}
                {% for error in form.username.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.username(class='form-control form-control-lg') }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.email.label(class='form-control-label') }}
            {%  if form.email.errors %}
                {{ form.email(class='form-control form-control-lg is-invalid') }}
                {% for error in form.email.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.email(class='form-control form-control-lg') }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.password.label(class='form-control-label') }}
            {%  if form.password.errors %}
                {{ form.password(class='form-control form-control-lg is-invalid') }}
                {% for error in form.password.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.password(class='form-control form-control-lg') }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.confirm_password.label(class='form-control-label') }}
            {%  if form.confirm_password.errors %}
                {{ form.confirm_password(class='form-control form-control-lg is-invalid') }}
                {% for error in form.confirm_password.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.confirm_password(class='form-control form-control-lg') }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class='btn btn-outline-info') }}
        </div>
    </form>
    <div class="border-top">
        <small>
            Already have accoutn? <a href="{{ url_for('users.login') }}">Login</a>
        </small>
    </div>
</div>
{% endblock content %}

app/flaskblog/templates/request_token.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section" style="width: 400px;">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.email.label(class='form-control-label') }}
            {%  if form.email.errors %}
                {{ form.email(class='form-control form-control-lg is-invalid') }}
                {% for error in form.email.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.email(class='form-control form-control-lg') }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class='btn btn-outline-info') }}
        </div>
    </form>
</div>
{% endblock %}

app/flaskblog/templates/reset_password.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section" style="width: 400px;">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.password.label(class='form-control-label') }}
            {%  if form.password.errors %}
                {{ form.password(class='form-control form-control-lg is-invalid') }}
                {% for error in form.password.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.password(class='form-control form-control-lg') }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.confirm_password.label(class='form-control-label') }}
            {%  if form.confirm_password.errors %}
                {{ form.confirm_password(class='form-control form-control-lg is-invalid') }}
                {% for error in form.confirm_password.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.confirm_password(class='form-control form-control-lg') }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class='btn btn-outline-info') }}
        </div>
    </form>
</div>
{% endblock content %}

app/flaskblog/templates/update_post.html
{% extends 'base.html' %}
{% block content %}
<div class="content-section" style="width: 400px;">
    <form action="" method="POST">
        {{ form.hidden_tag() }}
        <div class="form-group">
            {{ form.title.label(class='form-control-label') }}
            {%  if form.title.errors %}
                {{ form.title(class='form-control form-control-lg is-invalid') }}
                {% for error in form.title.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.title(class='form-control form-control-lg') }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.content.label(class='form-control-label') }}
            {%  if form.content.errors %}
                {{ form.content(class='form-control form-control-lg is-invalid') }}
                {% for error in form.content.errors %}
                    <span style="color: red;">{{ error }}</span>
                {% endfor %}
            {% else %}
                {{ form.content(class='form-control form-control-lg') }}
            {% endif %}
        </div>
        <div class="form-group">
            {{ form.submit(class='btn btn-outline-info') }}
        </div>
    </form>
</div>
{% endblock %}